import { SITE_URL } from "@/lib/site";

// ---------------------------------------------------------------------------
// robots.txt — served at /robots.txt
//
// Implemented as a Route Handler (not the app/robots.ts metadata convention)
// on purpose: robots.ts can only emit a structured object with no comments,
// and this policy needs inline comments plus a commented-out "opposite
// directive" under each AI training crawler so the block/allow choice can be
// flipped by hand without touching logic. The Sitemap line is generated from
// SITE_URL so it can never drift from the sitemap route.
// ---------------------------------------------------------------------------

export const dynamic = "force-static";

function robotsTxt(): string {
  return `# robots.txt for Zolomon Prints — prints.zolomon.studio
# Generated by app/robots.txt/route.ts. Edit there, not by hand.

# ===========================================================================
# AI RETRIEVAL / SEARCH CRAWLERS — always allowed.
# These are what make the shop eligible to be cited in ChatGPT, Claude, and
# Perplexity answers. Never block these.
# ===========================================================================
User-agent: OAI-SearchBot
Allow: /

User-agent: ChatGPT-User
Allow: /

User-agent: Claude-SearchBot
Allow: /

User-agent: Claude-User
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: Perplexity-User
Allow: /

# ===========================================================================
# AI TRAINING CRAWLERS — currently ALLOWED (Zol's choice, Sep 2026).
# To STOP your scans being used as AI training data, for each agent below
# comment out the "Allow: /" line and uncomment the "Disallow: /" line.
# This has NO effect on being cited in AI answers (that's the retrieval
# crawlers above) and NO effect on Google Search (see Googlebot below).
# ===========================================================================
User-agent: GPTBot
Allow: /
# Disallow: /

User-agent: ClaudeBot
Allow: /
# Disallow: /

User-agent: Google-Extended
Allow: /
# Disallow: /

User-agent: Applebot-Extended
Allow: /
# Disallow: /

User-agent: Meta-ExternalAgent
Allow: /
# Disallow: /

# ===========================================================================
# GOOGLE SEARCH — never block.
# Google-Extended (above) governs Gemini model TRAINING only. It has nothing
# to do with Google Search ranking or Google's AI Overviews / AI Mode, which
# are controlled by Googlebot. Keep this allowed.
# ===========================================================================
User-agent: Googlebot
Allow: /
Disallow: /api/
Disallow: /success

# ===========================================================================
# SCRAPER / DATA-BROKER CRAWLERS — blocked.
# ===========================================================================
User-agent: CCBot
Disallow: /

User-agent: Bytespider
Disallow: /

# ===========================================================================
# EVERYONE ELSE — crawl the content, stay out of transactional/API routes.
# This app has no /cart or /checkout page route: checkout is the /api/checkout
# handler and orders confirm at /success. Both are disallowed below.
# ===========================================================================
User-agent: *
Allow: /
Disallow: /api/
Disallow: /success

Sitemap: ${SITE_URL}/sitemap.xml
`;
}

export function GET() {
  return new Response(robotsTxt(), {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=86400"
    }
  });
}
